# Generated by Django 3.0.1 on 2019-12-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksliterators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literator',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='literators', to='booksliterators.Book'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='booksliterators.Book'),
        ),
    ]
