# Generated by Django 3.0.1 on 2019-12-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksliterators', '0002_auto_20191224_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='booksliterators.Book'),
        ),
    ]
