# Generated by Django 3.0.1 on 2019-12-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksliterators', '0003_auto_20191224_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
